### PR TITLE
Fix iPad preview removal on viewWillDisappear

### LINKED ISSUE #4: preview doesn't get removed during viewWillDisappear on iPad

### PR DESCRIPTION
**Pull request by neilmorton**
fixes issue where preview remained on screen (but not visible) after viewWillDisappear on iPad.
This fixes #4

### CODE REVIEW

File: VisualActivityViewController.swift [hunk 1]
```diff
@@ -183,8 +183,11 @@ final class VisualActivityViewController: UIActivityViewController {
     override func viewWillDisappear(_ animated: Bool) {
         super.viewWillDisappear(animated)
         
-        UIView.animate(withDuration: fadeOutDuration) {
-            self.preview?.alpha = 0
+        UIView.animate(withDuration: fadeOutDuration,
```
Comment (naturaln0va) [inline VisualActivityViewController.swift]: I prefer method signatures to only be on newlines if the signature is fairly long. Please put the `animation` parameter name on the same line as the duration parameter.

File: VisualActivityViewController.swift [hunk 2]
```diff
@@ -183,8 +183,11 @@ final class VisualActivityViewController: UIActivityViewController {
...
+                       animations: {
+                        self.preview?.alpha = 0;
+        }) { (Bool) in
```
Comment (naturaln0va) [inline VisualActivityViewController.swift]: Since the boolean parameter isn't used, replace it with an underscore.

File: VisualActivityViewController.swift [hunk 3]
```diff
@@ -183,8 +183,11 @@ final class VisualActivityViewController: UIActivityViewController {
...
+            self.preview? .removeFromSuperview()
```
Comment (naturaln0va) [inline VisualActivityViewController.swift]: Please remove the un-needed space between the question mark and the period.

**Review by naturaln0va — CHANGES_REQUESTED** [review]
Thanks for noticing this issue! Can you address these couple changes?

File: VisualActivityViewController.swift [hunk 4]
```diff
@@ -183,8 +183,10 @@ final class VisualActivityViewController: UIActivityViewController {
     override func viewWillDisappear(_ animated: Bool) {
         super.viewWillDisappear(animated)
         
-        UIView.animate(withDuration: fadeOutDuration) {
-            self.preview?.alpha = 0
+        UIView.animate(withDuration: fadeOutDuration, animations: {
+            self.preview?.alpha = 0;
+        }) {_ in
```
Comment (naturaln0va) [inline VisualActivityViewController.swift]:
```suggestion
        }) { _ in
```
Sorry for being picky, but can you add a space on the left side of the underscore?

Comment (neilmorton) [reply VisualActivityViewController.swift]: No problem. 1 minute.

**Comment by neilmorton** [comment]
Let me know how that looks.

File: VisualActivityViewController.swift [hunk 5]
```diff
@@ -183,8 +183,10 @@ final class VisualActivityViewController: UIActivityViewController {
     override func viewWillDisappear(_ animated: Bool) {
         super.viewWillDisappear(animated)
         
-        UIView.animate(withDuration: fadeOutDuration) {
-            self.preview?.alpha = 0
+        UIView.animate(withDuration: fadeOutDuration, animations: {
+            self.preview?.alpha = 0;
```
Comment (naturaln0va) [inline VisualActivityViewController.swift]:
```suggestion
            self.preview?.alpha = 0
```
One final thing, I missed this at first glance, can you remove the semi colon?

Comment (neilmorton) [reply VisualActivityViewController.swift]: Sorry, Objective C head in action there! Coming right up.

Comment (naturaln0va) [reply VisualActivityViewController.swift]: No problem, I've been there as well.

**Review by naturaln0va — APPROVED** [review]

**Comment by naturaln0va** [comment]
Thanks for getting this done @neilmorton! 👍
